[workspace]

members = [
  "crates/common",
  "crates/debug_label",
  "crates/react_refresh",
]

[profile.release]
# This removes more dead code
codegen-units = 1
lto = true
# Optimize for size
opt-level = "s"