[package]
authors = ["Mathis Møller"]
description = "Common code for jotai SWC plugins"
license = "MIT"
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.6.0"
swc_common = "0.29.10"
swc_core = { version = "0.40.11", features = ["ecma_ast"] }
