[package]
authors = ["Mathis Møller"]
description = "Common code for jotai SWC plugins"
license = "MIT"
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.156"
serde_json = "1.0.94"
swc_core = { version = "0.69.5", features = ["common", "ecma_ast"] }
