[package]
authors = ["Mathis Møller"]
description = "Common code for jotai SWC plugins"
license = "MIT"
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.28.9"
swc_core = { version = "0.25.17", features = ["ecma_ast"] }
