[package]
name = "swc_jotai_debug_label"
authors = ["Mathis Møller"]
description = "SWC plugin for automatic jotai atom debug labels"
license = "MIT"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
swc_common = "0.27.0"
swc_plugin = "0.88.1"

[dev-dependencies]
swc_ecma_parser = "0.116.0"
swc_ecma_transforms_base = "0.102.0"
swc_ecma_transforms_testing = "0.104.0"