[package]
name = "swc_jotai_debug_label"
authors = ["Mathis Møller"]
description = "SWC plugin for automatic jotai atom debug labels"
license = "MIT"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
swc_common = "0.27.13"
swc_core = { version = "0.14.0", features = [
  "ast", 
  "plugin_transform",
  "visit",
  "utils",
] }

[dev-dependencies]
swc_ecma_parser = "0.118.0"
swc_ecma_transforms_base = "0.105.0"
swc_ecma_transforms_testing = "0.107.0"