[package]
name = "swc_jotai_debug_label"
authors = ["Mathis Møller"]
description = "SWC plugin for automatic jotai atom debug labels"
license = "MIT"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
swc_common = "0.28.9"
swc_core = { version = "0.25.17", features = [
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "plugin_transform",
] }

[dev-dependencies]
swc_ecma_parser = "0.120.1"
swc_ecma_transforms_base = "0.109.1"
swc_ecma_transforms_testing = "0.111.2"
