[package]
name = "swc_jotai_debug_label"
authors = ["Mathis Møller"]
description = "SWC plugin for automatic jotai atom debug labels"
license = "MIT"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
common = { path = "../common" }
swc_common = "0.28.10"
swc_core = { version = "0.26.0", features = [
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "plugin_transform",
] }

[dev-dependencies]
swc_ecma_parser = "0.121.0"
swc_ecma_transforms_base = "0.110.0"
swc_ecma_transforms_testing = "0.112.0"
testing = "0.31.1"