[package]
name = "react_refresh"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_core = { version = "0.25.17", features = [
  "ecma_ast",
  "ecma_visit",
  "plugin_transform",
] }
